# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata: # kpt-merge: /wordpress-mysql
  name: wordpress-mysql
  labels:
    app: my-wordpress
    tier: mysql
  annotations:
    internal.kpt.dev/upstream-identifier: "|Service|default|wordpress-mysql"
    sample-annotation: sample-value
spec:
  selector:
    app: my-wordpress
    tier: mysql
  ports:
    - protocol: TCP
      port: 3306
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: # kpt-merge: /mysql-pv-claim
  name: mysql-pv-claim
  labels:
    app: my-wordpress
    tier: mysql
  annotations:
    internal.kpt.dev/upstream-identifier: "|PersistentVolumeClaim|default|mysql-pv-claim"
    sample-annotation: sample-value
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /wordpress-mysql
  name: wordpress-mysql
  labels:
    app: my-wordpress
    tier: mysql
  annotations:
    internal.kpt.dev/upstream-identifier: apps|Deployment|default|wordpress-mysql
    sample-annotation: sample-value
spec:
  selector:
    matchLabels:
      app: my-wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: my-wordpress
        tier: mysql
      annotations:
        sample-annotation: sample-value
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - name: mysql
              protocol: TCP
              containerPort: 3306
          resources:
            limits: {}
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "1"
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_DATABASE
              value: wordpress
            - valueFrom:
                secretKeyRef: {}
              name: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
  strategy:
    type: Recreate
