---
# Source: kuard/templates/general.sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "kuard-prod-general"
  namespace: "playground-helm"
  labels:
    app.kubernetes.io/component: general
    app.kubernetes.io/name: kuard
    app.helm.sh/release: "kuard-prod"
    app.helm.sh/chart: "kuard-0.0.0"
    app.skaffold.dev/artifact: "gcr_io_kuar_demo_kuard_amd64"
    app.skaffold.dev/tag: "v0_9_green"
---
# Source: kuard/templates/configs.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "kuard-prod-config-envs"
  namespace: "playground-helm"
  labels:
    app.kubernetes.io/name: kuard
    app.helm.sh/release: "kuard-prod"
    app.helm.sh/chart: "kuard-0.0.0"
    app.skaffold.dev/artifact: "gcr_io_kuar_demo_kuard_amd64"
    app.skaffold.dev/tag: "v0_9_green"
data:
  SECRET_A: "cHJvZCBTRUNSRVRfQQ=="
  SECRET_B: "cHJvZCBTRUNSRVRfQg=="
---
# Source: kuard/templates/configs.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "kuard-prod-config-files"
  namespace: "playground-helm"
  labels:
    app.kubernetes.io/name: kuard
    app.helm.sh/release: "kuard-prod"
    app.helm.sh/chart: "kuard-0.0.0"
    app.skaffold.dev/artifact: "gcr_io_kuar_demo_kuard_amd64"
    app.skaffold.dev/tag: "v0_9_green"
data:
  secret.json: "ewogICJkYXRhIjogInByb2Qgc2VjcmV0Lmpzb24iCn0K"
---
# Source: kuard/templates/configs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "kuard-prod-config-envs"
  namespace: "playground-helm"
  labels:
    app.kubernetes.io/name: kuard
    app.helm.sh/release: "kuard-prod"
    app.helm.sh/chart: "kuard-0.0.0"
    app.skaffold.dev/artifact: "gcr_io_kuar_demo_kuard_amd64"
    app.skaffold.dev/tag: "v0_9_green"
data:
  CONFIG_A: "prod CONFIG_A"
  CONFIG_B: "prod CONFIG_B"
---
# Source: kuard/templates/configs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "kuard-prod-config-files"
  namespace: "playground-helm"
  labels:
    app.kubernetes.io/name: kuard
    app.helm.sh/release: "kuard-prod"
    app.helm.sh/chart: "kuard-0.0.0"
    app.skaffold.dev/artifact: "gcr_io_kuar_demo_kuard_amd64"
    app.skaffold.dev/tag: "v0_9_green"
data:
  config.json: "{\n  \"data\": \"prod config.json\"\n}\n"
---
# Source: kuard/templates/http-server.svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "kuard-prod-http-server"
  namespace: "playground-helm"
  labels:
    app.kubernetes.io/component: http-server
    app.kubernetes.io/name: kuard
    app.helm.sh/release: "kuard-prod"
    app.helm.sh/chart: "kuard-0.0.0"
    app.skaffold.dev/artifact: "gcr_io_kuar_demo_kuard_amd64"
    app.skaffold.dev/tag: "v0_9_green"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: http-server
    app.kubernetes.io/name: kuard
    app.helm.sh/release: "kuard-prod"
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
---
# Source: kuard/templates/http-server.deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kuard-prod-http-server"
  namespace: "playground-helm"
  labels:
    app.kubernetes.io/component: http-server
    app.kubernetes.io/name: kuard
    app.helm.sh/release: "kuard-prod"
    app.helm.sh/chart: "kuard-0.0.0"
    app.skaffold.dev/artifact: "gcr_io_kuar_demo_kuard_amd64"
    app.skaffold.dev/tag: "v0_9_green"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: http-server
      app.kubernetes.io/name: kuard
      app.helm.sh/release: "kuard-prod"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: http-server
        app.kubernetes.io/name: kuard
        app.helm.sh/release: "kuard-prod"
        app.helm.sh/chart: "kuard-0.0.0"
        app.skaffold.dev/artifact: "gcr_io_kuar_demo_kuard_amd64"
        app.skaffold.dev/tag: "v0_9_green"
      annotations:
        checksum/configs: "7a96755025d8d8909d8b47b8f39b03e3c7ab2bb03167f02179fb319619a6b7e5"
    spec:
      serviceAccountName: "kuard-prod-general"
      containers:
        - name: http-server
          image: "gcr.io/kuar-demo/kuard-amd64:v0.9-green"
          envFrom:
            - configMapRef:
                name: "kuard-prod-config-envs"
            - secretRef:
                name: "kuard-prod-config-envs"
          volumeMounts:
            - name: config-files
              mountPath: /run/secrets/kuard
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /ready
          livenessProbe:
            httpGet:
              port: http
              path: /healthy
          resources:
            requests:
              cpu: 1m
              memory: 1M
            limits:
              cpu: 250m
              memory: 256M
      volumes:
        - name: config-files
          projected:
            sources:
              - configMap:
                  name: "kuard-prod-config-files"
              - secret:
                  name: "kuard-prod-config-files"
---
# Source: kuard/templates/http-server.hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "kuard-prod-http-server"
  namespace: "playground-helm"
  labels:
    app.kubernetes.io/component: http-server
    app.kubernetes.io/name: kuard
    app.helm.sh/release: "kuard-prod"
    app.helm.sh/chart: "kuard-0.0.0"
    app.skaffold.dev/artifact: "gcr_io_kuar_demo_kuard_amd64"
    app.skaffold.dev/tag: "v0_9_green"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "kuard-prod-http-server"
  minReplicas: 1
  maxReplicas: 2
