apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /http-server
  name: http-server
  labels:
    app.kubernetes.io/component: http-server
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|http-server'
spec:
  replicas: 1 # kpt-set: ${min-http-server-replicas}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: http-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: http-server
    spec:
      serviceAccountName: general
      containers:
        - name: http-server
          image: kuard
          envFrom:
            - configMapRef:
                name: config-envs
            - secretRef:
                name: config-envs
          volumeMounts:
            - name: config-files
              mountPath: /run/secrets/kuard
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /ready
          livenessProbe:
            httpGet:
              port: http
              path: /healthy
          resources:
            requests:
              cpu: 1m
              memory: 1M
            limits:
              cpu: 250m
              memory: 256M
      volumes:
        - name: config-files
          projected:
            sources:
              - configMap:
                  name: config-files
              - secret:
                  name: config-files
