apiVersion: v1
kind: Service
metadata: # kpt-merge: /http-server
  name: http-server
  labels:
    app.kubernetes.io/component: http-server
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|http-server'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: http-server
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
