apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /config-envs
  name: config-envs
  annotations:
    internal.kpt.dev/upstream-identifier: "|ConfigMap|default|config-envs"
data:
  CONFIG_A: test CONFIG_A
  CONFIG_B: test CONFIG_B
---
apiVersion: v1
kind: Secret
metadata: # kpt-merge: /config-envs
  name: config-envs
  annotations:
    internal.kpt.dev/upstream-identifier: "|Secret|default|config-envs"
type: Opaque
stringData:
  SECRET_A: test SECRET_A
  SECRET_B: test SECRET_B
---
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /config-files
  name: config-files
  annotations:
    internal.kpt.dev/upstream-identifier: "|ConfigMap|default|config-files"
data:
  config.json: |
    {
      "data": "test config.json"
    }
---
apiVersion: v1
kind: Secret
metadata: # kpt-merge: /config-files
  name: config-files
  annotations:
    internal.kpt.dev/upstream-identifier: "|Secret|default|config-files"
type: Opaque
stringData:
  secret.json: |
    {
      "data": "test secret.json"
    }
