apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-config-envs-prod
  namespace: playground-raw
  labels:
    app.kubernetes.io/name: kuard
    app.kubernetes.io/instance: prod
data:
  CONFIG_A: prod CONFIG_A
  CONFIG_B: prod CONFIG_B

---
apiVersion: v1
kind: Secret
metadata:
  name: kuard-config-envs-prod
  namespace: playground-raw
  labels:
    app.kubernetes.io/name: kuard
    app.kubernetes.io/instance: prod
type: Opaque
stringData:
  SECRET_A: prod SECRET_A
  SECRET_B: prod SECRET_B

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-config-files-prod
  namespace: playground-raw
  labels:
    app.kubernetes.io/name: kuard
    app.kubernetes.io/instance: prod
data:
  config.json: |
    {
      "data": "prod config.json"
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: kuard-config-files-prod
  namespace: playground-raw
  labels:
    app.kubernetes.io/name: kuard
    app.kubernetes.io/instance: prod
type: Opaque
stringData:
  secret.json: |
    {
      "data": "prod secret.json"
    }
