apiVersion: v1
kind: Service
metadata:
  name: kuard-http-server-prod
  namespace: playground-raw
  labels:
    app.kubernetes.io/name: kuard
    app.kubernetes.io/component: http-server
    app.kubernetes.io/instance: prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kuard
    app.kubernetes.io/component: http-server
    app.kubernetes.io/instance: prod
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
