apiVersion: skaffold/v3alpha1
kind: Config
profiles:
  - name: test
    manifests:
      helm:
        releases:
          - name: kuard-test
            namespace: playground-helm
            chartPath: charts/kuard
            valuesFiles:
              - releases/kuard-test/values.yaml
    deploy:
      kubeContext: docker-desktop
      kubectl:
        flags:
          global:
            - --namespace=playground-helm

  - name: prod
    manifests:
      helm:
        releases:
          - name: kuard-prod
            namespace: playground-helm
            chartPath: charts/kuard
            valuesFiles:
              - releases/kuard-prod/values.yaml
    deploy:
      kubeContext: docker-desktop
      kubectl:
        flags:
          global:
            - --namespace=playground-helm
