apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - general.sa.yaml
  - http-server.deploy.yaml
  - http-server.svc.yaml
configMapGenerator:
  - name: config-envs
  - name: config-files
secretGenerator:
  - name: config-envs
  - name: config-files
images:
  - name: kuard
    newName: gcr.io/kuar-demo/kuard-amd64
    newTag: v0.9-green
