apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - http-server.hpa.yaml
configMapGenerator:
  - name: config-envs
    envs:
      - configs/config.env
    behavior: merge
  - name: config-files
    files:
      - configs/config.json
    behavior: merge
secretGenerator:
  - name: config-envs
    envs:
      - configs/secret.env
    behavior: merge
  - name: config-files
    files:
      - configs/secret.json
    behavior: merge
namespace: playground-kustomize
namePrefix: kuard-
nameSuffix: -prod
commonLabels:
  app.kubernetes.io/name: kuard
  app.kubernetes.io/instance: prod
