apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-general"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: general
    {{- include "kuard.metadataLabels" $ | nindent 4 }}
