apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-config-envs-test
  namespace: playground-raw
data:
  CONFIG_A: test CONFIG_A
  CONFIG_B: test CONFIG_B

---
apiVersion: v1
kind: Secret
metadata:
  name: kuard-config-envs-test
  namespace: playground-raw
type: Opaque
stringData:
  SECRET_A: test SECRET_A
  SECRET_B: test SECRET_B

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-config-files-test
  namespace: playground-raw
data:
  config.json: |
    {
      "data": "test config.json"
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: kuard-config-files-test
  namespace: playground-raw
type: Opaque
stringData:
  secret.json: |
    {
      "data": "test secret.json"
    }
