apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: http-server
  labels:
    app.kubernetes.io/component: http-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-server
  minReplicas: 1
  maxReplicas: 2
